on:
  push:
    branches:
    - "master"
    pull_request:
    - "master"

name: test

jobs:
  test:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
       go-version: '>=1.19'
    - uses: actions/checkout@v3
    - run: go test ./... -coverprifile=coverage.out
    - name: report coverage
      uses: k1LoW/octocov-action@v0
  