on:
  push:
    branches:
    - "master"
    pull_request:
    - "master"

name: test

jobs:
  test:
    runs_on: ubuntu-latest
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - run: go test ./... -coverprifile=coverage.out
    - name: Run octocov
      uses: k1LoW/octocov-action@v0.46.0

  